### ISSUE TITLE
Should `Builder` methods return `self`?

### ISSUE THREAD

**Issue by bicarlsen** [JonasKruckenberg/tauri-sys#11]
In thinking about the ergonomics of the library, would it be nice for `Builder` methods -- e.g. [`FileDialogBuilder.set_default_path`](https://github.com/JonasKruckenberg/tauri-sys/blob/e638b5c289168b27a303492bfc7e931f13396d29/src/dialog.rs#L52) -- to return `self`?

This would allow method chaining turning, e.g.
```rust
let mut dialog = FileDialogBuilder::new();
dialog.set_title("Pick a file");
let file = dialog.pick_file().await;
``` 
into
```rust
let file = FileDialogBuilder::new()
    .set_title("Pick a file")
    .pick_file()
    .await;
```

**Comment by JonasKruckenberg** [comment]
All builders (I think) are now [non-consuming](https://doc.rust-lang.org/1.0.0/style/ownership/builders.html#non-consuming-builders-(preferred):) so it's a bit more tricky to do that, we cannot just return `Self` from methods, since we borrow `&mut self`.

But I'm thinking we can just make the final method take an `&self` instead of `self` since we never need ownership of the builder anyway 🤔 it just feels a bit weird to have the final method of a builder take `&self` but that's alright I guess

**Comment by JonasKruckenberg** [comment]
Update, it makes total sense for the final methods of each builder to only take immutable references to the builder bc all the js methods have to clone anyway

**Comment by bicarlsen** [comment]
Looks much more ergonomic now :)

**Comment by JonasKruckenberg** [comment]
Merged 😄
