### ISSUE TITLE
Help with `event::listener`

### ISSUE THREAD

**Issue by bicarlsen** [JonasKruckenberg/tauri-sys#15]
I am trying to use `event::listener` to react to events coming from the tauri backend in the frontend, but am having trouble actually consuming the result of `event::listen`.

Would it be possible to provide a more in-depth example or explanation than the one provided in the docs to help me understand how to use it?

**Comment by michalvavra** [comment]
I can't provide in-depth explanation, but feel free to look at my [`tauri-leptos-example`](https://github.com/michalvavra/tauri-leptos-example) repo. I'm using there `event::once` and `event::listen` (to continuously subscribe to stream of events).

One thing I've noticed is that you can only consume [window-specific](https://tauri.app/v1/guides/features/events/#window-specific-events-1) events (emitted from `Window`). It seembs to be because [`window_label`](https://github.com/JonasKruckenberg/tauri-sys/blob/0c864ee8c2b7d2eb44add60ca7973c9f2454f899/src/event.rs#L21) is required and being send, by Tauri, only for window-specific events.

**Comment by bicarlsen** [comment]
A code snippet that I got running:

```rust
use wasm_bindgen_futures::spawn_local;
use futures::stream::StreamExt;
use yew::prelude::*;

#[function_component(MyComponent)]
pub fn my_component() -> Html
    use_effect_with_deps(
            move |_| {
                spawn_local(async move {
                    // @todo: Listen to window events.
                    // @note: Used for *nix and macOS machines.
                    //      For Windows machine, look in the `Container` component.
                    let mut events = tauri_sys::event::listen::<i32>("tauri://file-drop")
                        .await
                        .expect("could not create `tauri://file-drop` listener");

                    while let Some(event) = events.next().await {
                        web_sys::console::log_1(&event.payload.into());
                    }
            });
        }
    )

    html! {}
}

**Comment by JonasKruckenberg** [comment]
closing this as it seems to not be an issue anymore?

**Comment by bicarlsen** [comment]
Yeah, thanks!
