### ISSUE TITLE
Tauri 2 compat ?

### ISSUE THREAD

**Issue by jrouaix** [JonasKruckenberg/tauri-sys#54]
Hello, we are trying to use this crate with Tauri 2, the command `invoke` seems to work.
Now the `event` part ... fail.
Do you think about maintaining these binding to Tauri 2 ?

(saying that with all due respect for the hard work you provided, and thankfull. I shamefully do not feel myself skilled enough to help, nor have time to give on this quest, and only can apologize for that :pray:  )

**Comment by madeofpendletonwool** [comment]
Hi @bicarlsen, thanks for starting this! There's for sure a need for this project to continue especially as wasm gets better and better. I maintain an app that uses the fs and tauri features and am eager for v2 support. I'd be happy to help you with development and assist with building those out. I'll go ahead and give it a fork and get to work!

**Comment by jrouaix** [comment]
I wonder if this shouldn't be part of the tauri's team burden to provide a rust api.
But in the same time, Tauri2 heavily rely on plugins JS injection ? So we are now talking about making 
- Rust bindings /
- on JS libs /
- calling Rust endpoints ?

m'I right ? (sounds like a clusterf... of problems ahead)

**Comment by bicarlsen** [comment]
@jrouaix You are correct, but as I said above the `tauri-bindgen` project isn't ready for v2 and has been dormant for quite some time according to those I spoke with on the Tauri team. This crate is meant to act as a stopgap for the moment until something more robust can be created.

Always happy to hear suggestions on other options.

In terms of it being the Tauri team's burden, from what I understand many (all?) of those working on the project don't get paid for it, and I'm sure this isn't at the top of their priority list for the v2 release (otherwise they would have implemented it). So given that they haven't done it yet, it's nice that we can build it ourselves until they release something official.

**Comment by JonasKruckenberg** [comment]
Hey guys, so first off awesome initiative!

As you have probably noticed I don't have the time to maintain these Tauri related tools as much as I used too, though revisiting tauri-bindgen is on my backlog (depending on a few internal factors at work)

that being said, I'd be happy @bicarlsen to make you coowner of this repo and make your endeavor "official" (as much as that is a thing at least) I think the best strategy while v1 is still widely used is to have separate branches for v1 and v2.

**Comment by madeofpendletonwool** [comment]
That's great! I love the idea of this picking back up. I'll make a fork of this repo directly then and pr directly into it. Yay for open source!

**Comment by bicarlsen** [comment]
@JonasKruckenberg Yeah, I'd be happy to help out :)

**Comment by bicarlsen** [comment]
This has been started on [branch `v2`](https://github.com/JonasKruckenberg/tauri-sys/tree/v2), so I'll close this issue.

If you want a specific feature, please open another issue for it.
